spring.application.name=emissionmap
spring.sql.init.mode=never
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.profiles.default=dev
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.keepalive-time=120000
spring.datasource.hikari.max-lifetime=300000
management.endpoints.web.exposure.include=health,info

emissionmap.geocoder.user-agent=emissionmap/0.0.1
emissionmap.lookup.default-radius-miles=3
emissionmap.lookup.max-radius-miles=10
emissionmap.lookup.default-year=2024
