spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.thymeleaf.cache=true
server.port=${PORT:8080}
server.forward-headers-strategy=framework

emissionmap.data.bootstrap-enabled=${EMISSIONMAP_DATA_BOOTSTRAP_ENABLED:false}
emissionmap.data.dir=${EMISSIONMAP_DATA_DIR:/tmp/emissionmap/data}
emissionmap.data.years=${EMISSIONMAP_DATA_YEARS:2022,2023,2024}
