-- Non-spatial tables — compatible with H2 (dev) and PostgreSQL (prod)

CREATE TABLE IF NOT EXISTS chemical_health_context (
    cas_number    VARCHAR(20)  PRIMARY KEY,
    chemical_name VARCHAR(255) NOT NULL,
    plain_name    VARCHAR(255) NOT NULL,
    health_note   TEXT         NOT NULL
);

CREATE TABLE IF NOT EXISTS lookup_audit (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    searched_at      TIMESTAMP    NOT NULL,
    address_state    CHAR(2),
    radius_miles     INTEGER,
    facilities_found INTEGER,
    nearest_dist_ft  INTEGER,
    geocoder_used    VARCHAR(20),
    resolved         BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS feedback (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_at TIMESTAMP    NOT NULL,
    page         VARCHAR(50),
    helpful      BOOLEAN,
    comment      TEXT
);

CREATE TABLE IF NOT EXISTS data_load_audit (
    dataset_name   VARCHAR(60)  PRIMARY KEY,
    loaded_at      TIMESTAMP    NOT NULL,
    reporting_year INTEGER,
    row_count      INTEGER      NOT NULL,
    load_status    VARCHAR(20)  NOT NULL,
    load_message   VARCHAR(500)
);
