-- PostGIS extension and TRI spatial tables
-- Skipped in H2 dev profile (cherry-pick V1 only)
-- Requires PostgreSQL with PostGIS extension available

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS tri_facilities (
    facility_id VARCHAR(50)      PRIMARY KEY,
    name        TEXT             NOT NULL,
    parent_co   TEXT,
    street      TEXT,
    city        TEXT,
    state       CHAR(2),
    zip         VARCHAR(10),
    lat         NUMERIC(9, 6)   NOT NULL,
    lng         NUMERIC(9, 6)   NOT NULL,
    geom        geometry(Point, 4326) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tri_facilities_geom
    ON tri_facilities USING GIST (geom);

CREATE TABLE IF NOT EXISTS tri_releases (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id     VARCHAR(50)     NOT NULL REFERENCES tri_facilities (facility_id),
    year            SMALLINT        NOT NULL,
    chemical        TEXT            NOT NULL,
    cas_number      VARCHAR(20),
    carcinogen      BOOLEAN         NOT NULL DEFAULT FALSE,
    pfas            BOOLEAN         NOT NULL DEFAULT FALSE,
    pbt             BOOLEAN         NOT NULL DEFAULT FALSE,
    air_fugitive    NUMERIC(14, 2),
    air_stack       NUMERIC(14, 2),
    water           NUMERIC(14, 2),
    on_site_total   NUMERIC(14, 2),
    unit_of_measure VARCHAR(20),
    UNIQUE (facility_id, year, chemical)
);

CREATE INDEX IF NOT EXISTS idx_tri_releases_facility ON tri_releases (facility_id);
CREATE INDEX IF NOT EXISTS idx_tri_releases_year     ON tri_releases (year);
